#
# Config file for `i3status-rust`
# https://github.com/greshake/i3status-rust
#

### Global variables:
icons_format = " {icon}"

### Icons/Themes
# https://github.com/greshake/i3status-rust/blob/master/doc/themes.md
[theme]
theme = "modern"
[icons]
icons = "awesome6"

### Blocks
# https://greshake.github.io/i3status-rust/i3status_rs/blocks/index.html
# https://greshake.github.io/i3status-rust/i3status_rs/formatting/index.html

[[block]]
block = "focused_window"
format = "$marks $visible_marks $title.str(max_w:80, rot_interval:0.25) | missing "

[[block]]
block = "load"
format = "$icon $1m.eng(w:4) "
interval = 5

[[block]]
block = "cpu"
format = "$icon $barchart ($utilization $frequency)"
interval = 1

[[block]]
block = "memory"
format     = "$icon $mem_used_percents.eng(w:2) "
format_alt = "$icon $mem_used / $mem_total (+$cached cached)"

[[block]]
block = "temperature"
format     = "$icon $average "
format_alt = "$icon $average avg, $min min, $max max "

# Uses `nvidia-smi` so might draw some extra power?
# [[block]]
# block = "nvidia_gpu"
# label = ""
# show_clocks = true
# show_memory = false
# show_utilization = true
# show_temperature = true
# show_power_draw = true

[[block]]
block = "custom"
command = "echo -n '\uf26c '; supergfxctl -S | tr -cd '[:alnum:]'"
interval = 15

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
format     = "$icon $available.eng(w:2) free"
format_alt = "$icon $available/$total"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "backlight"
cycle = [0, 50, 100, 50]

[[block]]
block = "custom"
cycle = ["gammastep -x; echo \uf186", "gammastep -O 3500; echo \uf2a8"]
interval = "once"

[[block]]
block = "battery"
format = "$icon $percentage ({$power|}, {$time|})"

[[block]]
block = "net"
format     = "$icon {$signal_strength|wired}^icon_net_down$speed_down.eng(prefix:K)^icon_net_up$speed_up.eng(prefix:K)"
format_alt = "$icon {$ssid |}$ip via $device"
interval = 5

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "/usr/bin/pavucontrol"

[[block]]
block = "time"
format = "$icon $timestamp.datetime(f:'%d.%m.%Y %R')"
interval = 5
[[block.click]]
button = "left"
cmd = "/usr/bin/gsimplecal"

[[block]]
block = "notify"
format = "$icon {$paused{Off}|On} "

