#
# Config file for `i3status-rust`
# https://github.com/greshake/i3status-rust
#

# https://github.com/greshake/i3status-rust/blob/master/doc/themes.md
theme = "modern"
icons = "awesome5"

# https://github.com/greshake/i3status-rust/blob/master/doc/blocks.md
[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "temperature"

[[block]]
block = "cpu"
format = "{utilization} ({boost}{frequency})"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents} ({swap_free}/{swap_total})"

# Uses `nvidia-smi` so might draw some extra power?
# [[block]]
# block = "nvidia_gpu"
# label = ""
# show_clocks = true
# show_memory = false
# show_utilization = true
# show_temperature = true
# show_power_draw = true

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "backlight"

[[block]]
block = "battery"
format = "{percentage} ({power}, {time})"

[[block]]
block = "net"
format = "{signal_strength}"
format_alt = "{ssid}: {ip} ({frequency}) {speed_down;K*b}/{speed_up;K*b}"
interval = 5

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "time"
format = "%V: %a %d.%m.%Y %R"
interval = 5
# on_click = calendar?

